defaults: &defaults
  geoipdat: config/GeoIP.dat
  only_latvia: false
  google_api: ABQIAAAAxRbqCxIbOGgElhIu7KGMFBTJQa0g3IQ9GZqIMmInSLzwtGDKaBQQ-ZTjZJ-tYo0txuieHFrSPCX2gQ
  
development:
  <<: *defaults
  only_latvia: false
  #popeye_url: http://popeye.local/cgi/popeye.sh
  #popeye_location: /usr/local/bin/py
  popeye_url: http://util.dia-x.info/cgi/popeye.sh
  popeye_location: /home/ike/cgi/py

test:
  <<: *defaults
  only_latvia: false

production:
  <<: *defaults
  google_api: ABQIAAAAxRbqCxIbOGgElhIu7KGMFBTj6X94sHzLUlcIj4CjtmwhSlzA9RSg47_WXwfUkVtW3Ig7xuhE0lrsYQ
  popeye_url: http://util.dia-x.info/cgi/popeye.sh
  popeye_location: /home/ike/cgi/py
  
