INSERT INTO l_users VALUES(1,'ike@ipro.lv','Iļja Ketris','qrFnApw/i5jeE','LV','','Iļja Ketris<br/>Viestura prospekts 95-84<br/>Rīga, LV-1005, LETTONIE<br/><br/>tel.+371 29 420 816; email &lt;ike@vo.id.lv&gt');
INSERT INTO l_users VALUES(2,'mary@jane.xx','Mary Jane','ejFiz8AkxAmhI','XX','',NULL);
INSERT INTO l_users VALUES(3,'janis@kudra.lv','Jānis Kūdra','iN5BKHac4HInc','LV','',NULL);
INSERT INTO l_users VALUES(4,'ion_murarasu@hotmail.com','Ion Murarasu','LVdvBgtG.VIpQ','RO','',NULL);
INSERT INTO l_users VALUES(5,'joaquimchessproblem@gmail.com','Joaquim Crusats','8fEyDXLE2o.qc','??','',NULL);
INSERT INTO l_users VALUES(6,'hubereric@yahoo.fr','Eric Huber','VqwyquDD1tnHM','RO','',NULL);
INSERT INTO l_users VALUES(7,'d@v.lv','AA','LwEdcgX8X0Qu6','LV','',NULL);
INSERT INTO l_users VALUES(8,'imurarasu@galati.astral.ro','Ion Murarasu','DbN7BmHm9BMaM','RO','',NULL);
INSERT INTO l_users VALUES(9,'egor@gde.to','Andrejs Jegorovs','651vu2Tvqt55c','LV','',NULL);
INSERT INTO l_users VALUES(10,'nikola.predrag@zg.t-com.hr','Nikola Prerag','6VYBLc7sNz11o','HR','',NULL);
INSERT INTO l_users VALUES(11,'vtyapkin@chess-problemist.com','Vladimir Tyapkin','7TK2DXq1CuT42','US','',NULL);
INSERT INTO l_users VALUES(12,'goja@goja.sk','Ján Golha','oq1synnPZ70tg','SK','',NULL);
INSERT INTO l_users VALUES(13,'szachista@verizon.net','Henryk Kalafut','WxYpbKbIwZYrU','us','',NULL);
INSERT INTO l_users VALUES(14,'kovzs@chello.hu','Zsolt Kovacs','ALek75eJgiYcU','HU','',NULL);
INSERT INTO l_users VALUES(15,'pogo5@free.fr','Christophe Prechac','MkyoZvYpQHUso','fr','',NULL);
INSERT INTO l_users VALUES(16,'cornelpacurar@gmail.com','Cornel Pacurar','Z7vyPaxZbxMng','CA','',NULL);
INSERT INTO l_users VALUES(17,'bdjurasevic@sbb.co.yu','Branislav Djurasevic','1jR/PS9PeGZxc','yu','',NULL);
INSERT INTO l_users VALUES(18,'ralf.kraetschmer@t-online.de','Ralf Krätschmer','3mNImFIiSUV9g','de','',NULL);
INSERT INTO l_users VALUES(19,'harryfou@ath.forthnet.gr','Harry Fougiaxis','R4v/ICoGHWfxc','GR','',NULL);
INSERT INTO l_users VALUES(20,'rudolf.larin@mail.ru',NULL,'4efBMHR6lv8Js',NULL,'',NULL);
INSERT INTO l_users VALUES(21,'wolper@xs4all.nl','wolper','VsisDyddg8Zn6','NL',NULL,NULL);
INSERT INTO l_users VALUES(22,'true.ishma@gmail.com','Maria','cpaxBObgMWMAI','LV',NULL,NULL);
INSERT INTO l_users VALUES(23,'ooo-berd@mail.ru','moda','PSHtsSi3SylvI','ru',NULL,NULL);
INSERT INTO l_users VALUES(24,'tmsarg@hotmail.com','Themis','dPETu/C3ocEO6','GR',NULL,NULL);
INSERT INTO l_users VALUES(25,'felchen@bluewin.ch','felchen','zRJLJ7aAPq/XU','CH',NULL,NULL);
INSERT INTO l_users VALUES(26,'rallovito@tin.it',NULL,'KDwVr8Yr3Tqd2',NULL,NULL,NULL);
INSERT INTO l_users VALUES(27,'marcel.fischer@gmx.ch','Marcel Fischer','c.TtmYVOuCdDU','CH',NULL,NULL);
INSERT INTO l_users VALUES(28,'prepress@printingtechnology.lv','Alexander Rudenko','F2O7vNpsOPNkA','LV',NULL,NULL);
INSERT INTO l_users VALUES(29,'sz.orlinski@wp.pl',NULL,'Eo2yRDqDr4Igg',NULL,NULL,NULL);
INSERT INTO l_users VALUES(30,'frank.richter.nbk@t-online.de','Frank Richter','4BVKsnJIpNNrA','DE',NULL,NULL);
INSERT INTO l_users VALUES(31,'ur@daveg.com','ULRICH RING','jAeG058CjAJ9Q','de',NULL,NULL);
INSERT INTO l_users VALUES(32,'shardul.golwalkar@gmail.com','terminator007','exmurM3zTLvnw','US',NULL,NULL);
INSERT INTO l_users VALUES(33,'h.le.grand@orange.nl','H. le Grand','8nKegdvyVtNIw','NL',NULL,NULL);
INSERT INTO l_users VALUES(34,'quarpaz1@yahoo.fr','raican','vd3wjMI96B7aY','ro',NULL,NULL);
INSERT INTO l_users VALUES(35,'yross@mail.ru','Rossomakho Yakov','Z85WJ4EnDb1sw','ru',NULL,NULL);
INSERT INTO l_users VALUES(36,'karste.wagner1@freenet.de','Karl Wagner','OccC0u0wyRg1I','DE',NULL,NULL);
INSERT INTO l_users VALUES(37,'joddy@ringrate.com',NULL,'ATu65mmQxLtd2',NULL,NULL,NULL);
INSERT INTO l_users VALUES(38,'borislav.gadjanski@gmail.com',NULL,'7NWKd7xMnkZfo',NULL,NULL,NULL);
INSERT INTO l_users VALUES(39,'izsib@hotmail.es','Imanol Zurutuza','A1K/mSzoXA//w','es',NULL,NULL);
INSERT INTO l_users VALUES(40,'kuzmisev@atknet.ru','vladimir','0/qz9hKbgz0kQ','ru',NULL,NULL);
INSERT INTO l_users VALUES(41,'smommaplete@gawab.com',NULL,'GpchTTugZ6sTg',NULL,NULL,NULL);
INSERT INTO l_users VALUES(42,'dmitri.turevski@gmail.com','Dmitri Turevski','sNPTLR52owA/I','ru',NULL,NULL);
INSERT INTO l_users VALUES(43,'gluismi@gmail.com','Luis Miguel Martín','KBACjimHYc5l.','es',NULL,NULL);
INSERT INTO l_users VALUES(44,'bds@bstephen.me.uk','Brian Stephenson','iRbV/QTdeOFHY','UK',NULL,NULL);
INSERT INTO l_users VALUES(45,'rsc@informatik.tu-chemnitz.de',NULL,'g4o.zXD.diTzY',NULL,NULL,NULL);
INSERT INTO l_users VALUES(46,'rftghfdghfew@lexs.name',NULL,'HfE0QG5LZohU.',NULL,NULL,NULL);
INSERT INTO l_users VALUES(47,'enzymnelono@mail.ru',NULL,'S7bXiXsCtmqBA',NULL,NULL,NULL);
INSERT INTO l_users VALUES(48,'liceactioft@gawab.com',NULL,'9lZg6w6pxFpA2',NULL,NULL,NULL);
INSERT INTO l_users VALUES(49,'lenipaype@gmail.com',NULL,'xldj9lgjDhvcA',NULL,NULL,NULL);
INSERT INTO l_users VALUES(50,'salgado.ronny96@gmail.com',NULL,'a2Qd1ErLXLjPE',NULL,NULL,NULL);
INSERT INTO l_users VALUES(51,'haprog@web.de','Hans Peter','fCfW9cMsZq/ko','DE',NULL,NULL);
INSERT INTO l_users VALUES(52,'rulacrusbal@gmail.com',NULL,'rp37c9zJQ010g',NULL,NULL,NULL);
INSERT INTO l_users VALUES(53,'audumberumbare@gmail.com','audu','b1DNRFJJPkdjY','91',NULL,NULL);
INSERT INTO l_users VALUES(54,'alurldeelslom@gmail.com',NULL,'qJjzZUJ7gXJEg',NULL,NULL,NULL);
INSERT INTO l_users VALUES(55,'mcroitor@gmail.com','Mihail','ZTVUVNZmtlud.','MD',NULL,NULL);
INSERT INTO l_users VALUES(56,'preofsrecremo@gmail.com',NULL,'FBPLKPxTO2fG2',NULL,NULL,NULL);
INSERT INTO l_users VALUES(57,'bitaalild@gmail.com',NULL,'CF6Alpgvoueqk',NULL,NULL,NULL);
INSERT INTO l_users VALUES(58,'info@chessstar.com',NULL,'h3n9unIYglOMU',NULL,NULL,NULL);
INSERT INTO l_users VALUES(59,'help@chessstar.com',NULL,'1U8gqoV3ESiKc',NULL,NULL,NULL);
INSERT INTO l_users VALUES(60,'mostaris22@gmail.com',NULL,'QRYChHbqHiD8o',NULL,NULL,NULL);
INSERT INTO l_users VALUES(61,'betapidelta@gmail.com','demos','KhiNtQ4h03.cg','gr',NULL,NULL);
INSERT INTO l_users VALUES(62,'areedbivins@gmail.com',NULL,'4LkA2VPc9Nh32',NULL,NULL,NULL);
INSERT INTO l_users VALUES(63,'gladyskerr0863@gmail.com',NULL,'7YEluTPS75EzE',NULL,NULL,NULL);
INSERT INTO l_users VALUES(64,'avittore1968@gmail.com',NULL,'7KigOCwwWntpM',NULL,NULL,NULL);
INSERT INTO l_users VALUES(65,'alterrelp@gmail.com',NULL,'q/9fWUGqyvYpA',NULL,NULL,NULL);
INSERT INTO l_users VALUES(66,'gesicennysi@gmail.com',NULL,'g/BvM6o0mv/nM',NULL,NULL,NULL);
INSERT INTO l_users VALUES(67,'cinkentendall@mail.ru',NULL,'Q00Q0WysBOYKY',NULL,NULL,NULL);
INSERT INTO l_users VALUES(68,'iclicki@hotmmail.com','iclicki','hweL05A4fLGSQ','BE',NULL,NULL);
INSERT INTO l_users VALUES(69,'iclicki@hotmail.com','iclicki','/BvEZRIqpcQ6A','be',NULL,NULL);
INSERT INTO l_users VALUES(70,'wineebiam@gmail.com',NULL,'4ET0HhArCipEo',NULL,NULL,NULL);
INSERT INTO l_users VALUES(71,'reginataitedeerriver@gmail.com',NULL,'nmOo0CPBFuAcw',NULL,NULL,NULL);
INSERT INTO l_users VALUES(72,'masseyturiddyke@gmail.com',NULL,'Q8ELd9RJEPKuw',NULL,NULL,NULL);
INSERT INTO l_users VALUES(73,'lianeaskew4388@gmail.com',NULL,'94iI60CAVXQdM',NULL,NULL,NULL);
INSERT INTO l_users VALUES(74,'nggsnlnsttrnggsnlnsttr4pt@gmail.com',NULL,'ruCLklzcrxFz6',NULL,NULL,NULL);
INSERT INTO l_users VALUES(75,'nggsnlnsttrnggsnlnsttr4ptti@gmail.com',NULL,'xUREyCWceofbk',NULL,NULL,NULL);
INSERT INTO l_users VALUES(76,'ewfxwefwef@gmail.com',NULL,'poxqJ65Cl723Q',NULL,NULL,NULL);
INSERT INTO l_users VALUES(77,'soannaroumn@gmail.com',NULL,'RbqTwFtPOvHAo',NULL,NULL,NULL);
INSERT INTO l_users VALUES(78,'falklandp1978@gmail.com',NULL,'4c0rM72MSseIc',NULL,NULL,NULL);
INSERT INTO l_users VALUES(79,'resther1963@gmail.com',NULL,'zj/fRJbSHrK4k',NULL,NULL,NULL);
INSERT INTO l_users VALUES(80,'shaea1989@gmail.com',NULL,'MOjvqzvCE5t.k',NULL,NULL,NULL);
INSERT INTO l_users VALUES(81,'xxxbester@gmail.com',NULL,'BMXOWzq2HWFO6',NULL,NULL,NULL);
INSERT INTO l_users VALUES(82,'dyndnsreg@gmail.com',NULL,'gZGMEieWFDa6w',NULL,NULL,NULL);
COMMIT;
